export const CHANGE_PASSPORT_START = "CHANGE_PASSPORT_START";
export const CHANGE_PASSPORT_SUCCESS = "CHANGE_PASSPORT_SUCCESS";
export const CHANGE_PASSPORT_FAIL = "CHANGE_PASSPORT_FAIL";
export const CHANGE_PASSPORT_CLEANUP = "CHANGE_PASSPORT_CLEANUP";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_CLEANUP = "CHANGE_PASSWORD_CLEANUP";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_CLEANUP = "LOGIN_CLEANUP";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_TOKEN_SUCCESS = "RESET_PASSWORD_TOKEN_SUCCESS";
export const RESET_PASSWORD_TOKEN_FAIL = "RESET_PASSWORD_TOKEN_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CLEANUP = "RESET_PASSWORD_CLEANUP";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SIGN_UP_CLEANUP = "SIGN_UP_CLEANUP";